version: '3'
services:
  backend:
    build: ./backend
    container_name: notes-backend
    env_file:
    - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: notes-frontend
    env_file:
    - ./frontend/.env 
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: