version: '3'
services:
  backend:
    build: ./backend
    container_name: notes-backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/notes
      - JWT_SECRET=secret123
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=http://frontend:5173
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    container_name: notes-frontend
    environment:
      - VITE_API_URL=http://backend:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: